name: "Website Healthcheck"
description: "Website status checking and text scanning"
branding:
  icon: activity
  color: white
inputs:
  web-url:
    description: "Specify the URL to scan"
    required: true
  scan-for-text:
    description: "Specify the string that has to be scanned"
    required: true
  max-attempts:
    description: "Number of attempts"
    required: false
    default: 3
  backoff-multiplier:
    description: "Number of seconds to increase backoff between attempts"
    required: false
    default: 2
runs:
  using: "composite"
  steps:
    - run: echo Scanning ${{ inputs.web-url }} for string ${{ inputs.scan-for-text }}
      shell: bash
    - run: chmod +x ${{ github.action_path }}/scan-website.sh
      shell: bash
    - run: ${{ github.action_path }}/scan-website.sh ${{ inputs.web-url }} ${{ inputs.scan-for-text }} ${{ inputs.max-attempts }} ${{ inputs.backoff-multiplier }}
      shell: bash
