name: "Website Healthcheck"
description: "Website status checking and text scanning"
branding:
  icon: activity
  color: white
inputs:
  web-url:
    description: "Specify the URL to scan"
    required: true
  scan-for-text:
    description: "Specify the string that has to be scanned"
    required: true
  retries:
    description: "Number of tries, default 3"
    required: false
  backoff_multiplier:
    description: "Number of seconds to sleep, will be multiplied by current try, default 2"
    required: false
runs:
  using: "composite"
  steps:
    - run: echo Scanning ${{ inputs.web-url }} for string ${{ inputs.scan-for-text }}
      shell: bash
    - run: chmod +x ${{ github.action_path }}/scan-website.sh
      shell: bash
    - run: ${{ github.action_path }}/scan-website.sh ${{ inputs.web-url }} ${{ inputs.scan-for-text }}
      shell: bash
